"""Update meal plan title to be unique

Revision ID: 39f32683ffb1
Revises: 9d269c9153c1
Create Date: 2022-08-04 04:00:50.091455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f32683ffb1'
down_revision = '9d269c9153c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meal_plan', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_plan', type_='unique')
    # ### end Alembic commands ###
