"""Rename meal attribute to title for meal plan model

Revision ID: 48b6397d0866
Revises: 85af2fa4e404
Create Date: 2022-07-28 20:57:45.553581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b6397d0866'
down_revision = '85af2fa4e404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('meal_plan', 'meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan', sa.Column('meal', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('meal_plan', 'title')
    # ### end Alembic commands ###
