"""Add additional attributes to meal plan model

Revision ID: 85af2fa4e404
Revises: 162b8dce4562
Create Date: 2022-07-28 20:19:18.878851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85af2fa4e404'
down_revision = '162b8dce4562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('meal_plan', sa.Column('diet', sa.String(), nullable=True))
    op.add_column('meal_plan', sa.Column('meal', sa.String(), nullable=False))
    op.add_column('meal_plan', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan', 'type')
    op.drop_column('meal_plan', 'meal')
    op.drop_column('meal_plan', 'diet')
    op.drop_column('meal_plan', 'calories')
    # ### end Alembic commands ###
